-- Create a private table for user profiles
create table profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  primary key (id),
  unique(username),
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create inventory table
create table inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text check (char_length(name) > 3),
  category text,
  quantity text,
  status text check (status in ('In Stock', 'Low Stock', 'Out of Stock')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for inventory
alter table inventory enable row level security;

create policy "Individuals can create inventory items."
  on inventory for insert
  with check ( auth.uid() = user_id );

create policy "Individuals can view their own inventory items. "
  on inventory for select
  using ( auth.uid() = user_id );

create policy "Individuals can update their own inventory items."
  on inventory for update
  using ( auth.uid() = user_id );

create policy "Individuals can delete their own inventory items."
  on inventory for delete
  using ( auth.uid() = user_id );
